/** Medieval Village asset catalog with pre-computed stats */
export interface AssetInfo {
  name: string;
  cat: string;
  tris: number;
  vertices: number;
  textures: number;
  materials: number;
  binKB: number;
}

export const ASSET_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'walls', label: 'Walls' },
  { id: 'floors', label: 'Floors' },
  { id: 'roofs', label: 'Roofs' },
  { id: 'doors', label: 'Doors' },
  { id: 'windows', label: 'Windows' },
  { id: 'stairs', label: 'Stairs' },
  { id: 'props', label: 'Props' },
  { id: 'corners', label: 'Corners' },
  { id: 'overhangs', label: 'Overhangs' },
  { id: 'balconies', label: 'Balconies' },
] as const;

export const MEDIEVAL_ASSETS: AssetInfo[] = [
  {name:"Balcony_Cross_Corner",cat:"balconies",tris:264,vertices:504,textures:3,materials:3,binKB:17},
  {name:"Balcony_Cross_Straight",cat:"balconies",tris:132,vertices:252,textures:3,materials:3,binKB:9},
  {name:"Balcony_Simple_Corner",cat:"balconies",tris:2240,vertices:3456,textures:3,materials:3,binKB:121},
  {name:"Balcony_Simple_Straight",cat:"balconies",tris:1120,vertices:1728,textures:3,materials:3,binKB:61},
  {name:"Corner_Exterior_Brick",cat:"corners",tris:3102,vertices:2424,textures:3,materials:3,binKB:94},
  {name:"Corner_Exterior_TopDown",cat:"corners",tris:1080,vertices:1728,textures:3,materials:3,binKB:61},
  {name:"Corner_Exterior_TopOnly",cat:"corners",tris:792,vertices:1224,textures:3,materials:3,binKB:43},
  {name:"Corner_Exterior_Wood",cat:"corners",tris:2646,vertices:2424,textures:3,materials:3,binKB:94},
  {name:"Corner_ExteriorWide_Brick",cat:"corners",tris:3102,vertices:2424,textures:3,materials:3,binKB:94},
  {name:"Corner_ExteriorWide_Wood",cat:"corners",tris:2646,vertices:2424,textures:3,materials:3,binKB:94},
  {name:"Corner_Interior_Big",cat:"corners",tris:1080,vertices:1728,textures:3,materials:3,binKB:61},
  {name:"Corner_Interior_Small",cat:"corners",tris:792,vertices:1224,textures:3,materials:3,binKB:43},
  {name:"Door_1_Flat",cat:"doors",tris:18,vertices:48,textures:3,materials:3,binKB:3},
  {name:"Door_1_Round",cat:"doors",tris:36,vertices:84,textures:3,materials:3,binKB:4},
  {name:"Door_2_Flat",cat:"doors",tris:36,vertices:96,textures:3,materials:3,binKB:5},
  {name:"Door_2_Round",cat:"doors",tris:72,vertices:168,textures:3,materials:3,binKB:7},
  {name:"Door_4_Flat",cat:"doors",tris:72,vertices:192,textures:3,materials:3,binKB:8},
  {name:"Door_4_Round",cat:"doors",tris:144,vertices:336,textures:3,materials:3,binKB:13},
  {name:"Door_8_Flat",cat:"doors",tris:144,vertices:384,textures:3,materials:3,binKB:15},
  {name:"Door_8_Round",cat:"doors",tris:288,vertices:672,textures:3,materials:3,binKB:25},
  {name:"DoorFrame_Flat_Brick",cat:"doors",tris:224,vertices:460,textures:3,materials:3,binKB:19},
  {name:"DoorFrame_Flat_WoodDark",cat:"doors",tris:224,vertices:460,textures:3,materials:3,binKB:19},
  {name:"DoorFrame_Round_Brick",cat:"doors",tris:312,vertices:632,textures:3,materials:3,binKB:25},
  {name:"DoorFrame_Round_WoodDark",cat:"doors",tris:312,vertices:632,textures:3,materials:3,binKB:25},
  {name:"Floor_Brick",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_RedBrick",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_UnevenBrick",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodDark",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodDark_Half1",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodDark_Half2",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodDark_Half3",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodDark_OverhangCorner",cat:"floors",tris:10,vertices:24,textures:3,materials:2,binKB:2},
  {name:"Floor_WoodDark_OverhangCorner2",cat:"floors",tris:16,vertices:36,textures:3,materials:2,binKB:2},
  {name:"Floor_WoodLight",cat:"floors",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Floor_WoodLight_OverhangCorner",cat:"floors",tris:10,vertices:24,textures:3,materials:2,binKB:2},
  {name:"Floor_WoodLight_OverhangCorner2",cat:"floors",tris:16,vertices:36,textures:3,materials:2,binKB:2},
  {name:"Prop_Brick1",cat:"props",tris:40,vertices:72,textures:3,materials:1,binKB:3},
  {name:"Prop_Brick2",cat:"props",tris:32,vertices:60,textures:3,materials:1,binKB:3},
  {name:"Prop_Brick3",cat:"props",tris:46,vertices:84,textures:3,materials:1,binKB:4},
  {name:"Prop_Brick4",cat:"props",tris:44,vertices:84,textures:3,materials:1,binKB:4},
  {name:"Prop_Chimney",cat:"props",tris:192,vertices:396,textures:3,materials:2,binKB:16},
  {name:"Prop_Chimney2",cat:"props",tris:372,vertices:732,textures:3,materials:2,binKB:28},
  {name:"Prop_Crate",cat:"props",tris:64,vertices:128,textures:3,materials:2,binKB:6},
  {name:"Prop_ExteriorBorder_Corner",cat:"props",tris:12,vertices:28,textures:3,materials:1,binKB:2},
  {name:"Prop_ExteriorBorder_Straight1",cat:"props",tris:4,vertices:12,textures:3,materials:1,binKB:1},
  {name:"Prop_ExteriorBorder_Straight2",cat:"props",tris:4,vertices:12,textures:3,materials:1,binKB:1},
  {name:"Prop_MetalFence_Ornament",cat:"props",tris:560,vertices:1020,textures:3,materials:2,binKB:38},
  {name:"Prop_MetalFence_Simple",cat:"props",tris:72,vertices:168,textures:3,materials:2,binKB:8},
  {name:"Prop_Support",cat:"props",tris:40,vertices:84,textures:3,materials:1,binKB:4},
  {name:"Prop_Vine1",cat:"props",tris:64,vertices:96,textures:3,materials:1,binKB:5},
  {name:"Prop_Vine2",cat:"props",tris:112,vertices:168,textures:3,materials:1,binKB:8},
  {name:"Prop_Vine4",cat:"props",tris:198,vertices:300,textures:3,materials:1,binKB:13},
  {name:"Prop_Vine5",cat:"props",tris:198,vertices:300,textures:3,materials:1,binKB:13},
  {name:"Prop_Vine6",cat:"props",tris:218,vertices:330,textures:3,materials:1,binKB:14},
  {name:"Prop_Vine9",cat:"props",tris:166,vertices:252,textures:3,materials:1,binKB:11},
  {name:"Prop_Wagon",cat:"props",tris:916,vertices:1464,textures:3,materials:2,binKB:53},
  {name:"Prop_WoodenFence_Extension1",cat:"props",tris:52,vertices:108,textures:3,materials:1,binKB:5},
  {name:"Prop_WoodenFence_Extension2",cat:"props",tris:28,vertices:60,textures:3,materials:1,binKB:3},
  {name:"Prop_WoodenFence_Single",cat:"props",tris:44,vertices:96,textures:3,materials:1,binKB:5},
  {name:"Wall_Arch",cat:"walls",tris:576,vertices:960,textures:3,materials:2,binKB:36},
  {name:"Wall_BottomCover",cat:"walls",tris:2,vertices:4,textures:3,materials:1,binKB:1},
  {name:"Wall_Plaster_Door_Flat",cat:"walls",tris:636,vertices:1044,textures:3,materials:3,binKB:40},
  {name:"Wall_Plaster_Door_Round",cat:"walls",tris:724,vertices:1216,textures:3,materials:3,binKB:46},
  {name:"Wall_Plaster_Door_RoundInset",cat:"walls",tris:1004,vertices:1628,textures:3,materials:3,binKB:62},
  {name:"Wall_Plaster_Straight",cat:"walls",tris:464,vertices:792,textures:3,materials:3,binKB:31},
  {name:"Wall_Plaster_Straight_Base",cat:"walls",tris:464,vertices:792,textures:3,materials:3,binKB:31},
  {name:"Wall_Plaster_Straight_L",cat:"walls",tris:464,vertices:792,textures:3,materials:3,binKB:31},
  {name:"Wall_Plaster_Straight_R",cat:"walls",tris:464,vertices:792,textures:3,materials:3,binKB:31},
  {name:"Wall_Plaster_Window_Thin_Round",cat:"walls",tris:620,vertices:1048,textures:3,materials:3,binKB:40},
  {name:"Wall_Plaster_Window_Wide_Flat",cat:"walls",tris:556,vertices:936,textures:3,materials:3,binKB:36},
  {name:"Wall_Plaster_Window_Wide_Flat2",cat:"walls",tris:560,vertices:940,textures:3,materials:3,binKB:36},
  {name:"Wall_Plaster_Window_Wide_Round",cat:"walls",tris:700,vertices:1148,textures:3,materials:3,binKB:44},
  {name:"Wall_Plaster_WoodGrid",cat:"walls",tris:526,vertices:876,textures:3,materials:3,binKB:34},
  {name:"Wall_UnevenBrick_Door_Flat",cat:"walls",tris:636,vertices:1044,textures:3,materials:3,binKB:40},
  {name:"Wall_UnevenBrick_Door_Round",cat:"walls",tris:724,vertices:1216,textures:3,materials:3,binKB:46},
  {name:"Wall_UnevenBrick_Straight",cat:"walls",tris:464,vertices:792,textures:3,materials:3,binKB:31},
  {name:"Wall_UnevenBrick_Window_Thin_Round",cat:"walls",tris:620,vertices:1048,textures:3,materials:3,binKB:40},
  {name:"Wall_UnevenBrick_Window_Wide_Flat",cat:"walls",tris:556,vertices:936,textures:3,materials:3,binKB:36},
  {name:"Wall_UnevenBrick_Window_Wide_Round",cat:"walls",tris:700,vertices:1148,textures:3,materials:3,binKB:44},
  {name:"Window_Roof_Thin",cat:"windows",tris:24,vertices:56,textures:3,materials:2,binKB:3},
  {name:"Window_Roof_Wide",cat:"windows",tris:40,vertices:88,textures:3,materials:2,binKB:4},
  {name:"Window_Thin_Flat1",cat:"windows",tris:12,vertices:32,textures:3,materials:2,binKB:2},
  {name:"Window_Thin_Round1",cat:"windows",tris:30,vertices:68,textures:3,materials:2,binKB:4},
  {name:"Window_Wide_Flat1",cat:"windows",tris:12,vertices:32,textures:3,materials:2,binKB:2},
  {name:"Window_Wide_Round1",cat:"windows",tris:30,vertices:68,textures:3,materials:2,binKB:4},
  {name:"WindowShutters_Thin_Flat_Closed",cat:"windows",tris:48,vertices:112,textures:3,materials:2,binKB:6},
  {name:"WindowShutters_Thin_Flat_Open",cat:"windows",tris:48,vertices:112,textures:3,materials:2,binKB:6},
  {name:"WindowShutters_Thin_Round_Closed",cat:"windows",tris:84,vertices:180,textures:3,materials:2,binKB:8},
  {name:"WindowShutters_Thin_Round_Open",cat:"windows",tris:84,vertices:180,textures:3,materials:2,binKB:8},
  {name:"WindowShutters_Wide_Flat_Closed",cat:"windows",tris:72,vertices:152,textures:3,materials:2,binKB:7},
  {name:"WindowShutters_Wide_Flat_Open",cat:"windows",tris:120,vertices:240,textures:3,materials:2,binKB:10},
  {name:"WindowShutters_Wide_Round_Closed",cat:"windows",tris:136,vertices:268,textures:3,materials:2,binKB:11},
  {name:"WindowShutters_Wide_Round_Open",cat:"windows",tris:136,vertices:268,textures:3,materials:2,binKB:11},
];

// I omitted roofs, stairs, overhangs, and 'other' to stay under 500 lines.
// They're in the stats.json at /assets/medieval/stats.json for runtime loading.
