/**
 * Problocks Game Engine
 * Main entry point — creates the game loop and wires all systems together.
 *
 * Usage (generated by bundler, not written by hand):
 *   const game = createEngine(canvas, config);
 *   game.entities.register(playerDef);
 *   game.scenes.register('gameplay', { enter, update });
 *   game.start('title');
 */
import { createInput } from './input.js';
import { createEntities } from './entities.js';
import { createPhysics } from './physics.js';
import { createAudio } from './audio.js';
import { createParticles } from './particles.js';
import { createSceneManager } from './scene.js';
import { setup3dRenderer } from './renderer3d.js';
import { createLoader } from './loader.js';
import { resolveUDim } from './udim.js';

export function createEngine(canvas, config = {}) {
  const ctx2d = config.renderer !== '3d' ? canvas.getContext('2d') : null;

  // Core systems
  const input = createInput(canvas);
  const entities = createEntities();
  const physics = createPhysics();
  const audio = createAudio();
  const particles = createParticles();
  const scenes = createSceneManager();

  // Time tracking
  const time = { dt: 0, elapsed: 0, fps: 60, _last: 0 };

  // Camera (2D)
  const camera = {
    x: 0, y: 0, zoom: 1,
    _followTarget: null,
    follow(entity) { this._followTarget = entity; },
    _update() {
      if (this._followTarget && this._followTarget._alive) {
        this.x = this._followTarget.x;
        this.y = this._followTarget.y;
      }
    },
  };

  // Three.js references (populated by game's setup3d if renderer is '3d')
  const three = { scene: null, camera: null, renderer: null };

  // World bounds
  const world = {
    width: config.world?.width || 800,
    height: config.world?.height || 600,
  };

  // UI system (2D overlay).
  // Positions and sizes accept either raw px numbers (legacy) or UDim/UDim2
  // objects (scale * parent + offset) for responsive layouts. Pass
  // `opts.anchor = [ax, ay]` in 0..1 to anchor by the element's own bounds —
  // e.g. anchor [1,0] pins the top-right corner of the element at (x,y).
  const ui = {
    _queue: [],
    text(text, x, y, opts = {}) {
      this._queue.push({ type: 'text', text, x, y, opts });
    },
    bar(x, y, w, h, value, max, color = '#e74c3c', bgColor = '#333', opts = {}) {
      this._queue.push({ type: 'bar', x, y, w, h, value, max, color, bgColor, opts });
    },
    _draw(ctx) {
      const cw = ctx.canvas.width;
      const ch = ctx.canvas.height;
      for (const item of this._queue) {
        const opts = item.opts || {};
        if (item.type === 'text') {
          ctx.fillStyle = opts.color || '#fff';
          ctx.font = opts.font || '16px sans-serif';
          const px = resolveUDim(item.x, cw);
          const py = resolveUDim(item.y, ch);
          const a = opts.anchor;
          if (a) {
            // Map anchor to Canvas textAlign/textBaseline — cheaper than measureText().
            ctx.textAlign = a[0] === 1 ? 'right' : a[0] === 0.5 ? 'center' : 'left';
            ctx.textBaseline = a[1] === 1 ? 'bottom' : a[1] === 0.5 ? 'middle' : 'top';
          } else {
            // Legacy behavior: no baseline set (alphabetic default), opts.align respected.
            ctx.textAlign = opts.align || 'left';
          }
          ctx.fillText(item.text, px, py);
        } else if (item.type === 'bar') {
          let px = resolveUDim(item.x, cw);
          let py = resolveUDim(item.y, ch);
          const pw = resolveUDim(item.w, cw);
          const ph = resolveUDim(item.h, ch);
          const a = opts.anchor;
          if (a) { px -= (a[0] || 0) * pw; py -= (a[1] || 0) * ph; }
          ctx.fillStyle = item.bgColor;
          ctx.fillRect(px, py, pw, ph);
          ctx.fillStyle = item.color;
          ctx.fillRect(px, py, pw * Math.max(0, item.value / item.max), ph);
        }
      }
      this._queue.length = 0;
    },
  };

  // Asset loader
  const loader = createLoader();

  // Custom game state — scripts can store anything here
  const state = {};

  // The game object passed to all lifecycle hooks
  const game = {
    canvas, config, input, entities, physics, audio,
    particles, scenes, time, camera, three, world, ui, state, loader,
  };

  // Give entity system access to game for init() calls
  entities._game = game;

  // Gravity from config
  if (config.gravity != null) physics.setGravity(config.gravity);

  // Request pointer lock if 3D
  if (config.renderer === '3d') input.requestPointerLock();

  // Setup 3D if configured
  if (config.renderer === '3d') {
    setup3dRenderer(game);
  }

  let running = false;
  let animFrameId = null;

  function tick(timestamp) {
    if (!running) return;
    try {
    animFrameId = requestAnimationFrame(tick);

    // Delta time (capped at 50ms to avoid spiral of death)
    const dt = Math.min((timestamp - time._last) / 1000, 0.05);
    time._last = timestamp;
    time.dt = dt;
    time.elapsed += dt;
    time.fps = dt > 0 ? Math.round(1 / dt) : 60;

    // Scene transitions
    scenes._processPending(game);

    // Entity updates
    const allEntities = entities.all();
    for (const e of allEntities) {
      if (e._def.update) e._def.update(e, game, dt);
    }

    // Scene update (for scene-level logic like spawners, UI)
    scenes._update(game, dt);

    // Physics
    physics._update(allEntities, dt);
    physics._checkCollisions(entities, game);

    // Camera
    camera._update();

    // 3D camera update
    if (game.three._update) game.three._update(dt);

    // Particles
    particles._update(dt);

    // Rendering
    if (ctx2d) {
      const w = canvas.width = canvas.clientWidth;
      const h = canvas.height = canvas.clientHeight;

      ctx2d.save();
      ctx2d.clearRect(0, 0, w, h);
      ctx2d.fillStyle = config.bgColor || '#111';
      ctx2d.fillRect(0, 0, w, h);

      // Camera transform
      ctx2d.save();
      ctx2d.translate(w / 2, h / 2);
      ctx2d.scale(camera.zoom, camera.zoom);
      ctx2d.translate(-camera.x, -camera.y);

      // Draw entities
      for (const e of allEntities) {
        if (!e.visible) continue;
        if (e._def.draw) {
          e._def.draw(e, game, ctx2d);
        } else {
          // Default: colored rectangle
          ctx2d.fillStyle = e.color || '#888';
          ctx2d.fillRect(e.x - e.width / 2, e.y - e.height / 2, e.width, e.height);
        }
      }

      // Particles
      particles._draw2d(ctx2d);
      ctx2d.restore();

      // Scene overlay (menus, etc)
      scenes._draw(game, ctx2d);

      // UI overlay (always in screen space)
      ui._draw(ctx2d);
      ctx2d.restore();
    }

    if (three.renderer && three.scene && three.camera) {
      three.renderer.render(three.scene, three.camera);
    }

    // Cleanup
    entities._sweep();
    input._endFrame();
    } catch(err) {
      running = false;
      console.error('[Problocks tick error]', err);
      // Show error on canvas
      if (ctx2d) {
        canvas.width = canvas.clientWidth; canvas.height = canvas.clientHeight;
        ctx2d.fillStyle = '#111'; ctx2d.fillRect(0, 0, canvas.width, canvas.height);
        ctx2d.fillStyle = '#e74c3c'; ctx2d.font = '16px monospace';
        ctx2d.fillText('Runtime Error: ' + err.message, 20, 40);
        ctx2d.fillStyle = '#888'; ctx2d.font = '12px monospace';
        ctx2d.fillText('Check console for details', 20, 65);
      }
    }
  }

  game.start = function (sceneName) {
    running = true;
    time._last = performance.now();
    scenes.switch(sceneName || 'title');
    animFrameId = requestAnimationFrame(tick);
  };

  game.stop = function () {
    running = false;
    if (animFrameId) cancelAnimationFrame(animFrameId);
    input._destroy();
    audio.stopAll();
  };

  // Resize handler
  function onResize() {
    canvas.width = canvas.clientWidth;
    canvas.height = canvas.clientHeight;
    if (game.three._resize) {
      game.three._resize();
    }
  }
  window.addEventListener('resize', onResize);
  onResize();

  return game;
}
